CodeEditApp/CodeEditLanguages

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sources/CodeEditLanguages/Resources/tree-sitter-bash/highlights.scm
Since the SPM additions were merged into the master branch of `tree-sitter-bash` we now use the master branch directly.
> [chore]: using tree-sitter-bash master branch now

- build_framework.sh
implement green status messages.
by default hide any xcodebuild output.
use '--debug' to display verbose output.
> update build script

- Package.resolved
- Package.swift
Since we now use `xcodebuild docbuild` to build DocC documentation, the `swift-docs-plugin` is no longer needed.
> remove swift-docc-plugin since it is no longer needed

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CodeLanguages-Container/CodeLanguages-Container/CodeLanguages_Container.h
- README.md
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Documentation.docc/CodeLanguage.md
- Sources/CodeEditLanguages/Documentation.docc/TreeSitterModel.md
- Sources/CodeEditLanguages/Resources/tree-sitter-cpp/injections.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-dockerfile/highlights.scm
- Sources/CodeEditLanguages/TreeSitterLanguage.swift
- Sources/CodeEditLanguages/TreeSitterModel.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
- add `Dockerfile` support
- update `C#` and `C++` grammars
> [feat] Add Dockerfile support

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
- add `.jav` file extension to Java language definition (closes #18)
- update C# language parser
- move language definitions to `CodeLangauge+Definitions.swift`
> [feat]: add `.jav` file extension to Java language definition

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sources/CodeEditLanguages/Resources/tree-sitter-yaml/highlights.scm
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
Since a lot of `tree-sitter` language parser repositories seem to be inactive and a [PR](https://github.com/ikatyang/tree-sitter-yaml/pull/41) to add highlights to YAML is still not being reviewed, I added the file to a forked branch.
The result in `CodeEdit` will look something like this:
Refs: https://github.com/CodeEditApp/CodeEdit/discussions/1021
> [feat]: Add YAML highlights

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CodeLanguages-Container/CodeLanguages-Container/CodeLanguages_Container.h
- README.md
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Documentation.docc/CodeLanguage.md
- Sources/CodeEditLanguages/Documentation.docc/TreeSitterModel.md
- Sources/CodeEditLanguages/Resources/tree-sitter-java/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-sql/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-swift/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-zig/highlights.scm
- Sources/CodeEditLanguages/TreeSitterLanguage.swift
- Sources/CodeEditLanguages/TreeSitterModel.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
This PR adds the [`tree-sitter-sql`](https://github.com/lukepistrol/tree-sitter-sql/tree/feature/spm) parser to `CodeEditLanguages`.
> The parser is still a fork of the official repo. It might stay that way, since the official repo does not track the `src/parser.c` file but relies on generating it on-the-fly using `node`.
Other language parsers have been updated to their latest versions:
- C
- C#
- C++
- Dockerfile
- Haskell
- Java
- JavaScript
- PHP
- Rust
- Swift
- Zig
> [feat]: Add SQL parser

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CodeLanguages-Container/CodeLanguages-Container/CodeLanguages_Container.h
- README.md
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Documentation.docc/CodeLanguage.md
- Sources/CodeEditLanguages/Documentation.docc/TreeSitterModel.md
- Sources/CodeEditLanguages/Resources/tree-sitter-lua/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-lua/injections.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-lua/locals.scm
- Sources/CodeEditLanguages/TreeSitterLanguage.swift
- Sources/CodeEditLanguages/TreeSitterModel.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
This PR adds the [`tree-sitter-lua`](https://github.com/lukepistrol/tree-sitter-lua/tree/feature/spm) parser.
Note that the parser's repo is still a fork and not the official one.
> [feat]: Add `Lua` Parser

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CodeLanguages-Container/CodeLanguages-Container/CodeLanguages_Container.h
- README.md
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Resources/tree-sitter-regex/highlights.scm
- Sources/CodeEditLanguages/TreeSitterLanguage.swift
- Sources/CodeEditLanguages/TreeSitterModel.swift
Adds support for the regex language. Regex doesn't have a standalone file type so the `extensions` array is left empty.
In action in CodeEdit *(CE doesn't syntax highlight any punctuation pairs but it shows the @ symbol and numbers being parsed)*:
> Add Regex Language

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CodeLanguages-Container/CodeLanguages-Container/CodeLanguages_Container.h
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Documentation.docc/CodeLanguage.md
- Sources/CodeEditLanguages/Documentation.docc/TreeSitterModel.md
- Sources/CodeEditLanguages/Resources/tree-sitter-markdown-inline/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-markdown-inline/injections.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-markdown/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-markdown/injections.scm
- Sources/CodeEditLanguages/TreeSitterLanguage.swift
- Sources/CodeEditLanguages/TreeSitterModel.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
Adds support for the Markdown Grammar. Unlike, #38 this one supports highlighting and injections.
CodeEditApp/CodeEditTextView#187 fixes a Markdown highlighting bug.
* #10
* #38 
* CodeEditApp/CodeEditTextView#187
> Add Markdown Grammar (w/ Highlighting)

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- README.md
- Sources/CodeEditLanguages/Resources/tree-sitter-ocaml/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-ocaml/tags.scm
- build_framework.sh
Resubmission of #43 following merge conflicts created by #42.
Original Description:
> PR #24 added support for OCaml via a fork I created.
> 
> Since then, the [official repository](https://github.com/tree-sitter/tree-sitter-ocaml) has been updated with SPM support. This PR switches the `tree-sitter-ocaml` dependency to the official repository.
> 
> Additionally, minor changes were made to the build script to ignore test targets, which `tree-sitter-ocaml` has.
* #42 
* #43
> Update `tree-sitter-ocaml` Dependency to Official Repository (Resubmission)

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CodeLanguages-Container/CodeLanguages-Container/CodeLanguages_Container.h
- README.md
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Documentation.docc/CodeLanguage.md
- Sources/CodeEditLanguages/Documentation.docc/TreeSitterModel.md
- Sources/CodeEditLanguages/Resources/tree-sitter-jsdoc/highlights.scm
- Sources/CodeEditLanguages/TreeSitterLanguage.swift
- Sources/CodeEditLanguages/TreeSitterModel.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
Add support for `JSDoc`.
* #10
> Add `JSDoc` Grammar

- Package.swift
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage+DetectLanguage.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Tests/CodeEditLanguagesTests/LanguageDetectionTests.swift
Adds shebang and mode line detection to the `CodeLanguage.detectLanguage` function.
Shebangs are commonly used in scripting languages like python or ruby to allow the scripts to be run by the operating system by adding a "#! ..." line at the top of the file.
modelines are used by Emacs and Vim to configure editor functionality. Both have parameters for setting the file type.
`CodeLanguage.detectLanguage` can now detect both shebangs and modelines via the optional parameters `prefixBuffer` and `suffixBuffer`. It will check the prefix buffer for a valid shebang, and if found attempt to parse it. If no shebang is found, it will attempt to find and parse a valid modeline from either the prefix or suffix (Emacs modelines can be in the first or last 5 lines of the file).
* closes #46 
Once the …
> Shebang and Modeline Detection

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CodeLanguages-Container/CodeLanguages-Container/CodeLanguages_Container.h
- README.md
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Documentation.docc/CodeLanguage.md
- Sources/CodeEditLanguages/Documentation.docc/TreeSitterModel.md
- Sources/CodeEditLanguages/Resources/tree-sitter-toml/highlights.scm
- Sources/CodeEditLanguages/TreeSitterLanguage.swift
- Sources/CodeEditLanguages/TreeSitterModel.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
> Add `TOML` Grammar

- Sources/CodeEditLanguages/TreeSitterModel.swift
Fixes a bad access error on Dart due to a typo calling the wrong method.
> Fix EXE_BAD_ACCESS error on Dart

- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
I've added `c++` extension to known extensions of cpp, to allow recognition of files of this extension as c plus plus ones
N/A
N/A
> add:  `c++` extension to `cpp` known extensions 🔨

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CodeLanguages-Container/CodeLanguages-Container/CodeLanguages_Container.h
- README.md
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Documentation.docc/CodeLanguage.md
- Sources/CodeEditLanguages/Documentation.docc/TreeSitterModel.md
- Sources/CodeEditLanguages/TreeSitterLanguage.swift
- Sources/CodeEditLanguages/TreeSitterModel.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
Adds support for the 4 no-highlight grammars in the `README`, being:
- `Agda`
- `Julia`
- `Perl`
- `Verilog`
All but `Agda` use their official repo.
* #10
> Add `Agda`, `Julia`, `Perl`, and `Verilog` Grammars

- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Tests/CodeEditLanguagesTests/CodeEditLanguagesTests.swift
Adds `shtml` as a file extension under HTML.
* Closes #53
> Add `shtml` extension to known `HTML` extensions

- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
Add `cjs` and `mjs` as known `javascript` extensions and `cts` and `mts` as known typescript extensions.
* resolve #57
n/a
Signed-off-by: Qian Qian "Cubik"‎ <cubik65536@cubik65536.top>
> Add more JavaScript and TypeScript extensions

- build_framework.sh
Fix framework symlink resolution error by add -y to zip command in build_framework.sh
The `CodeLanguagesContainer.xcframework.zip` is currently generated using the following command:
```bash
zip -r -q "$OUTPUT_PATH".zip "$OUTPUT_PATH"
```
This method stores multiple copies of symlinked files, which may trigger warnings in recent versions of Xcode (I have observed this from Xcode 15.3), as well as in Xcode Cloud. It also fails AppStore Connect and TestFlight validations.
The solution is to simply add the `-y` option to the zip command, which also reduces the size of the `CodeLanguagesContainer.xcframework.zip` to about one-third of the original size. However, I have not updated the zip file in this pull request to avoid breaking anything.
Reference: …
> Fix framework symlink resolution error by add -y to zip command in build_framework.sh

- build_framework.sh
Updates build script to build a fat binary for both x86 and arm. New zip file is 33MB, which is still 1/3 the size it was before 56edd6e200ebd43d940d93045960698439396c6f.
> Update Build Script, Include `arm` and `x86`

- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
Signed-off-by: Qian Qian "Cubik"‎ <cubik65536@cubik65536.top>
Add comment string definitions for each language so the feature to press `⌘` + `/` to comment a line or a block of codes can be provided.
* _n/a_
_n/a_
> feat: Define comment strings for each language

- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.pbxproj
- CodeLanguages-Container/CodeLanguages-Container.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.resolved
- Package.swift
- README.md
- Sources/CodeEditLanguages/CodeLanguage+Definitions.swift
- Sources/CodeEditLanguages/CodeLanguage.swift
- Sources/CodeEditLanguages/Resources/tree-sitter-agda/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-dart/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-dart/tags.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-dart/test.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-kotlin/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-lua/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-lua/tags.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-markdown-inline/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-objc/folds.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-objc/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-objc/indents.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-objc/injections.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-objc/locals.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-regex/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-yaml/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-zig/folds.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-zig/highlights.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-zig/indents.scm
- Sources/CodeEditLanguages/Resources/tree-sitter-zig/injections.scm
- Bumps SwiftTreeSitter to `0.9.0` - which bumps tree-sitter to `0.23.2`
- Updates language sources for sources that now support SPM on the main branch
- Updates ObjC to inherit from the C grammar
All updates:
Language | Original User | Original Branch | New User | New Branch
-- | -- | -- | -- | --
Agda | cengelbart39 | feat/spm | tree-sitter | master
Dart | lukepistrol | feat/spm | UserNobody14 | master
Kotlin | lukepistrol | feat/spm-queries | fwcd | main
Lua | lukepistrol | feat/spm | tree-sitter-grammars | main
Markdown | MDeiml | split_parser | tree-sitter-grammars | split_parser
ObjC | lukepistrol | feature/spm | tree-sitter-grammars | master
Regex | thecoolwinter | feature/spm | tree-sitter | master
YAML | lukepistrol | feature/spm | tree-sitter-grammars | master
Zig | maxxnino (no …
> chore: Update Language Sources
